# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
